type = "batch"
timelimit = "3s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
3
a
aa
ab
'''
out = '''
1
499122179
499122179
'''

[[cases]]
name = "sample2"
in = '''
3
a
aa
aaa
'''
out = '''
1
2
3
'''
