type = "batch"
timelimit = "2s"
match = "float"

[float]
relative-error = 1e-9
absolute-error = 1e-9

[[cases]]
name = "sample1"
in = '''
2 3 1 2
'''
out = '''
3.000000 0
'''

[[cases]]
name = "sample2"
in = '''
2 2 1 1
'''
out = '''
2.000000 1
'''
