type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
7 4
AB?A?BA
'''
out = '''
1
'''

[[cases]]
name = "sample2"
in = '''
40 7
????????????????????????????????????????
'''
out = '''
116295436
'''

[[cases]]
name = "sample3"
in = '''
15 5
ABABA??????????
'''
out = '''
0
'''

[[cases]]
name = "sample4"
in = '''
40 8
?A?B??B?B?AA?A?B??B?A???B?BB?B???BA??BAA
'''
out = '''
259240
'''
