type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
123233
'''
out = '''
Yes
'''

[[cases]]
name = "sample2"
in = '''
123234
'''
out = '''
No
'''

[[cases]]
name = "sample3"
in = '''
323132
'''
out = '''
Yes
'''

[[cases]]
name = "sample4"
in = '''
500000
'''
out = '''
No
'''
