type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
3 100 50
60 20 40
'''
out = '''
70
'''

[[cases]]
name = "sample2"
in = '''
3 100 50
60000 20000 40000
'''
out = '''
100
'''
