type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
WACWA
'''
out = '''
ACCAC
'''

[[cases]]
name = "sample2"
in = '''
WWA
'''
out = '''
ACC
'''

[[cases]]
name = "sample3"
in = '''
WWWWW
'''
out = '''
WWWWW
'''
