type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
4 5
100 4 60 1 4
'''
out = '''
160
'''

[[cases]]
name = "sample2"
in = '''
10 1
5000 2 2000 1 300
'''
out = '''
20000
'''

[[cases]]
name = "sample3"
in = '''
9 23
170 8 120 5 12
'''
out = '''
650
'''

[[cases]]
name = "sample4"
in = '''
653 314159
6728 123456 5141 41928 222222
'''
out = '''
2818162
'''
