type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
4 3
3543
'''
out = '''
6
'''

[[cases]]
name = "sample2"
in = '''
4 2
2020
'''
out = '''
10
'''

[[cases]]
name = "sample3"
in = '''
20 11
33883322005544116655
'''
out = '''
68
'''
