type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
yay
'''
out = '''
5
'''

[[cases]]
name = "sample2"
in = '''
aababc
'''
out = '''
17
'''

[[cases]]
name = "sample3"
in = '''
abracadabra
'''
out = '''
54
'''
