type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
2 3
TTT
T.T
'''
out = '''
PCT
T.T
'''

[[cases]]
name = "sample2"
in = '''
3 5
TTT..
.TTT.
TTTTT
'''
out = '''
PCT..
.PCT.
PCTPC
'''
