type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
12 18
'''
out = '''
3
'''

[[cases]]
name = "sample2"
in = '''
420 660
'''
out = '''
4
'''

[[cases]]
name = "sample3"
in = '''
1 2019
'''
out = '''
1
'''
