type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
0 0 0 4 5 6
2 3 4 5 6 7
'''
out = '''
Yes
'''

[[cases]]
name = "sample2"
in = '''
0 0 0 2 2 2
0 0 2 2 2 4
'''
out = '''
No
'''

[[cases]]
name = "sample3"
in = '''
0 0 0 1000 1000 1000
10 10 10 100 100 100
'''
out = '''
Yes
'''
