type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
5 2
3 1 5 4 9
'''
out = '''
2
'''

[[cases]]
name = "sample2"
in = '''
6 5
1 1 1 1 1 1
'''
out = '''
0
'''

[[cases]]
name = "sample3"
in = '''
8 3
31 43 26 6 18 36 22 13
'''
out = '''
18
'''
