type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
contest
son
'''
out = '''
10
'''

[[cases]]
name = "sample2"
in = '''
contest
programming
'''
out = '''
-1
'''

[[cases]]
name = "sample3"
in = '''
contest
sentence
'''
out = '''
33
'''
