type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
7777
'''
out = '''
Weak
'''

[[cases]]
name = "sample2"
in = '''
0112
'''
out = '''
Strong
'''

[[cases]]
name = "sample3"
in = '''
9012
'''
out = '''
Weak
'''
