type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
5 10
6 11 21 22 30
'''
out = '''
Yes
'''

[[cases]]
name = "sample2"
in = '''
2 100
1 200
'''
out = '''
No
'''

[[cases]]
name = "sample3"
in = '''
10 22
47 81 82 95 117 146 165 209 212 215
'''
out = '''
No
'''
