type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
10 4
1 6
4 5
5 10
7 10
'''
out = '''
1
'''

[[cases]]
name = "sample2"
in = '''
5 2
1 2
3 4
'''
out = '''
0
'''

[[cases]]
name = "sample3"
in = '''
5 10
2 5
1 5
1 2
2 4
2 2
5 5
2 4
1 2
2 2
2 3
'''
out = '''
3
'''
