type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
2 9
1 4 8 5
'''
out = '''
Alice
'''

[[cases]]
name = "sample2"
in = '''
3 998244353
1 2 3 1 2 3
'''
out = '''
Bob
'''
