type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
ABCDEFGHIJKLMNOPQRSTUVWXYZ
'''
out = '''
25
'''

[[cases]]
name = "sample2"
in = '''
MGJYIZDKSBHPVENFLQURTCWOAX
'''
out = '''
223
'''
