type = "batch"
timelimit = "2s"
match = "float"

[float]
relative-error = 1e-6
absolute-error = 1e-6

[[cases]]
name = "sample1"
in = '''
3
1
2
3
'''
out = '''
18.8495559215
'''

[[cases]]
name = "sample2"
in = '''
6
15
2
3
7
6
9
'''
out = '''
508.938009881546
'''
