type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
january
february
march
april
may
june
july
august
september
october
november
december
'''
out = '''
8
'''

[[cases]]
name = "sample2"
in = '''
rrrrrrrrrr
srrrrrrrrr
rsr
ssr
rrs
srsrrrrrr
rssrrrrrr
sss
rrr
srr
rsrrrrrrrr
ssrrrrrrrr
'''
out = '''
11
'''
