type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
12
'''
out = '''
5
'''

[[cases]]
name = "sample2"
in = '''
345
'''
out = '''
175
'''

[[cases]]
name = "sample3"
in = '''
999999999
'''
out = '''
900000000
'''
