type = "batch"
timelimit = "10s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
20
'''
out = '''
13
'''

[[cases]]
name = "sample2"
in = '''
2024
'''
out = '''
409
'''

[[cases]]
name = "sample3"
in = '''
9876543210
'''
out = '''
547452239
'''
