type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
3 5 10
East 7
West 3
West 11
'''
out = '''
West 8
'''

[[cases]]
name = "sample2"
in = '''
3 3 8
West 6
East 3
East 1
'''
out = '''
0
'''

[[cases]]
name = "sample3"
in = '''
5 25 25
East 1
East 1
West 1
East 100
West 1
'''
out = '''
East 25
'''
