type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
2017/01/07
'''
out = '''
2018/01/07
'''

[[cases]]
name = "sample2"
in = '''
2017/01/31
'''
out = '''
2018/01/31
'''
