type = "batch"
timelimit = "2s"
match = "float"

[float]
relative-error = 1e-6
absolute-error = 1e-6

[[cases]]
name = "sample1"
in = '''
3 2 2 3
'''
out = '''
0.222222222222222
'''

[[cases]]
name = "sample2"
in = '''
10 1 10 1
'''
out = '''
1.000000000000000
'''

[[cases]]
name = "sample3"
in = '''
100 10 10 2
'''
out = '''
0.401263060761621
'''
