type = "batch"
timelimit = "2s"
match = "float"

[float]
relative-error = 1e-9
absolute-error = 1e-9

[[cases]]
name = "sample1"
in = '''
3 4 9 0
'''
out = '''
5.00000000000000000000
'''

[[cases]]
name = "sample2"
in = '''
3 4 10 40
'''
out = '''
4.56425719433005567605
'''
