type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
-13 3
'''
out = '''
-10
'''

[[cases]]
name = "sample2"
in = '''
1 -33
'''
out = '''
34
'''

[[cases]]
name = "sample3"
in = '''
13 3
'''
out = '''
39
'''
