type = "batch"
timelimit = "4s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
4 1
1 1 2 1
'''
out = '''
3
'''

[[cases]]
name = "sample2"
in = '''
3 3
1 1 2
'''
out = '''
1
'''

[[cases]]
name = "sample3"
in = '''
10 4
2 7 1 8 2 8 1 8 2 8
'''
out = '''
132
'''
