type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
2
3 2
7 5
'''
out = '''
3
'''

[[cases]]
name = "sample2"
in = '''
3
1 5 3
10 7 3
'''
out = '''
0
'''

[[cases]]
name = "sample3"
in = '''
3
3 2 5
6 9 8
'''
out = '''
2
'''
