type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
3 5 4
'''
out = '''
YES
'''

[[cases]]
name = "sample2"
in = '''
2 2 6
'''
out = '''
NO
'''

[[cases]]
name = "sample3"
in = '''
5 3 2
'''
out = '''
NO
'''
