type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
5 3 3
1 2 4
'''
out = '''
1
'''

[[cases]]
name = "sample2"
in = '''
7 3 2
4 5 6
'''
out = '''
0
'''

[[cases]]
name = "sample3"
in = '''
10 7 5
1 2 3 4 6 8 9
'''
out = '''
3
'''
