type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
Takahashi Chokudai
'''
out = '''
Takahashi san
'''

[[cases]]
name = "sample2"
in = '''
K Eyence
'''
out = '''
K san
'''
