type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
aBc
'''
out = '''
2
'''

[[cases]]
name = "sample2"
in = '''
xxxxxxXxxx
'''
out = '''
7
'''

[[cases]]
name = "sample3"
in = '''
Zz
'''
out = '''
1
'''
