type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
9
'''
out = '''
3
'''

[[cases]]
name = "sample2"
in = '''
119
'''
out = '''
10
'''

[[cases]]
name = "sample3"
in = '''
10000000
'''
out = '''
24
'''
