type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
100 1 2
'''
out = '''
101
'''

[[cases]]
name = "sample2"
in = '''
100 2 1
'''
out = '''
99
'''

[[cases]]
name = "sample3"
in = '''
100 1 1
'''
out = '''
100
'''
