type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
atcoder toe
'''
out = '''
Yes
'''

[[cases]]
name = "sample2"
in = '''
beginner r
'''
out = '''
No
'''

[[cases]]
name = "sample3"
in = '''
verticalreading agh
'''
out = '''
No
'''
