type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
atcoder|beginner|contest
'''
out = '''
atcodercontest
'''

[[cases]]
name = "sample2"
in = '''
|spoiler|
'''
out = ''''''

[[cases]]
name = "sample3"
in = '''
||xyz
'''
out = '''
xyz
'''
