type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
bacdefghijklmnopqrstuvwxzy
4
abx
bzz
bzy
caa
'''
out = '''
bzz
bzy
abx
caa
'''

[[cases]]
name = "sample2"
in = '''
zyxwvutsrqponmlkjihgfedcba
5
a
ab
abc
ac
b
'''
out = '''
b
a
ac
ab
abc
'''
