type = "batch"
timelimit = "2s"
match = "float"

[float]
relative-error = 1e-3
absolute-error = 1e-3

[[cases]]
name = "sample1"
in = '''
1000
'''
out = '''
10
'''

[[cases]]
name = "sample2"
in = '''
50
'''
out = '''
0.5
'''

[[cases]]
name = "sample3"
in = '''
3141
'''
out = '''
31.41
'''
