type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
3
5
#.#
...
..#
'''
out = '''
5
'''

[[cases]]
name = "sample2"
in = '''
2
2
#.
.#
'''
out = '''
0
'''

[[cases]]
name = "sample3"
in = '''
8
8
........
........
........
........
........
........
........
........
'''
out = '''
64678
'''
