type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
4 4 4
1 2 3
3 2 2
2 1 2
2 4 1
'''
out = '''
2
4
3
4
'''

[[cases]]
name = "sample2"
in = '''
382 382 3
3 3 3
8 8 8
2 2 2
'''
out = '''
382
382
381
'''

[[cases]]
name = "sample3"
in = '''
5 10 8
2 2 1
4 3 1
4 8 2
1 2 2
2 5 3
5 4 3
4 5 2
1 5 2
'''
out = '''
5
5
5
4
3
5
4
2
'''
