type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
5
'''
out = '''
HellWorld
'''

[[cases]]
name = "sample2"
in = '''
9
'''
out = '''
HelloWord
'''

[[cases]]
name = "sample3"
in = '''
1
'''
out = '''
elloWorld
'''
