type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
2
algorithm heuristic
'''
out = '''
24
'''

[[cases]]
name = "sample2"
in = '''
3
i love you
'''
out = '''
459
'''
