type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
50 7
40 8
30 9
'''
out = '''
94
'''

[[cases]]
name = "sample2"
in = '''
990 10
990 10
990 10
'''
out = '''
2970
'''
