type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
5
'''
out = '''
3 5 7 11 31
'''

[[cases]]
name = "sample2"
in = '''
6
'''
out = '''
2 3 5 7 11 13
'''

[[cases]]
name = "sample3"
in = '''
8
'''
out = '''
2 5 7 13 19 37 67 79
'''
