type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
324
'''
out = '''
Yes
'''

[[cases]]
name = "sample2"
in = '''
5
'''
out = '''
No
'''

[[cases]]
name = "sample3"
in = '''
32
'''
out = '''
Yes
'''

[[cases]]
name = "sample4"
in = '''
37748736
'''
out = '''
Yes
'''
