type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
4 3
1 2
2 3
1 4
'''
out = '''
3
'''

[[cases]]
name = "sample2"
in = '''
3 0
'''
out = '''
0
'''

[[cases]]
name = "sample3"
in = '''
10 8
1 2
2 3
3 4
4 5
6 7
7 8
8 9
9 10
'''
out = '''
12
'''
