type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
80 94
'''
out = '''
2
'''

[[cases]]
name = "sample2"
in = '''
1000 63
'''
out = '''
0
'''

[[cases]]
name = "sample3"
in = '''
270 750
'''
out = '''
48
'''
