type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
2 4
'''
out = '''
6
'''

[[cases]]
name = "sample2"
in = '''
1 1
'''
out = '''
2
'''

[[cases]]
name = "sample3"
in = '''
123456789000 123456789050
'''
out = '''
2125824
'''
