type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
1.012
'''
out = '''
1.012
'''

[[cases]]
name = "sample2"
in = '''
12.340
'''
out = '''
12.34
'''

[[cases]]
name = "sample3"
in = '''
99.900
'''
out = '''
99.9
'''

[[cases]]
name = "sample4"
in = '''
0.000
'''
out = '''
0
'''
