type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
99
'''
out = '''
63
'''

[[cases]]
name = "sample2"
in = '''
12
'''
out = '''
0C
'''

[[cases]]
name = "sample3"
in = '''
0
'''
out = '''
00
'''

[[cases]]
name = "sample4"
in = '''
255
'''
out = '''
FF
'''
