type = "batch"
timelimit = "4s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
6
1 2 4 6 7 271
'''
out = '''
4
'''

[[cases]]
name = "sample2"
in = '''
10
1 1 1 1 1 1 1 1 1 1
'''
out = '''
5
'''

[[cases]]
name = "sample3"
in = '''
1
5
'''
out = '''
0
'''
