type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
3 5
'''
out = '''
0
'''

[[cases]]
name = "sample2"
in = '''
4 5
'''
out = '''
2
'''

[[cases]]
name = "sample3"
in = '''
5 5
'''
out = '''
4
'''

[[cases]]
name = "sample4"
in = '''
100000 2
'''
out = '''
1
'''

[[cases]]
name = "sample5"
in = '''
100000 100000
'''
out = '''
50000
'''
