type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
1 5 2
'''
out = '''
53
'''

[[cases]]
name = "sample2"
in = '''
9 9 9
'''
out = '''
108
'''

[[cases]]
name = "sample3"
in = '''
6 6 7
'''
out = '''
82
'''
