type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
azzel
apple
'''
out = '''
Yes
'''

[[cases]]
name = "sample2"
in = '''
chokudai
redcoder
'''
out = '''
No
'''

[[cases]]
name = "sample3"
in = '''
abcdefghijklmnopqrstuvwxyz
ibyhqfrekavclxjstdwgpzmonu
'''
out = '''
Yes
'''
