type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
DD??S
'''
out = '''
676
'''

[[cases]]
name = "sample2"
in = '''
????????????????????????????????????????
'''
out = '''
858572093
'''

[[cases]]
name = "sample3"
in = '''
?D??S
'''
out = '''
136604
'''
