type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
4
WWRR
'''
out = '''
2
'''

[[cases]]
name = "sample2"
in = '''
2
RR
'''
out = '''
0
'''

[[cases]]
name = "sample3"
in = '''
8
WRWWRWRR
'''
out = '''
3
'''
