type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
2 4
'''
out = '''
5
'''

[[cases]]
name = "sample2"
in = '''
123 456
'''
out = '''
435
'''

[[cases]]
name = "sample3"
in = '''
123456789012 123456789012
'''
out = '''
123456789012
'''
