type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
3 2 6
abc
xxx
abc
'''
out = '''
abcxxx
'''

[[cases]]
name = "sample2"
in = '''
5 5 416
a
aa
aaa
aa
a
'''
out = '''
aaaaaaa
'''
