type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
6 4
-10 8 2 1 2 6
'''
out = '''
14
'''

[[cases]]
name = "sample2"
in = '''
6 4
-6 -100 50 -2 -5 -3
'''
out = '''
44
'''

[[cases]]
name = "sample3"
in = '''
6 3
-6 -100 50 -2 -5 -3
'''
out = '''
0
'''
