type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
1199
'''
out = '''
ABC
'''

[[cases]]
name = "sample2"
in = '''
1200
'''
out = '''
ARC
'''

[[cases]]
name = "sample3"
in = '''
4208
'''
out = '''
AGC
'''
