type = "batch"
timelimit = "5s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
3 2
1 4
2 5
0 6
'''
out = '''
Yes
4
2
0
'''

[[cases]]
name = "sample2"
in = '''
3 3
1 4
2 5
0 6
'''
out = '''
No
'''
