type = "batch"
timelimit = "5s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
abcbcba
'''
out = '''
21
'''

[[cases]]
name = "sample2"
in = '''
mississippi
'''
out = '''
53
'''

[[cases]]
name = "sample3"
in = '''
ababacaca
'''
out = '''
33
'''

[[cases]]
name = "sample4"
in = '''
aaaaa
'''
out = '''
5
'''
