type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
2 2 4
'''
out = '''
baab
'''

[[cases]]
name = "sample2"
in = '''
30 30 118264581564861424
'''
out = '''
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
'''
