type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
3
Takahashi
Aoki
Snuke
'''
out = '''
Snuke
Aoki
Takahashi
'''

[[cases]]
name = "sample2"
in = '''
4
2023
Year
New
Happy
'''
out = '''
Happy
New
Year
2023
'''
