type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
1 1
5 6
'''
out = '''
2
'''

[[cases]]
name = "sample2"
in = '''
1 1
1 200001
'''
out = '''
2
'''

[[cases]]
name = "sample3"
in = '''
2 3
998244353 998244853
'''
out = '''
3
'''

[[cases]]
name = "sample4"
in = '''
1 1
1 1
'''
out = '''
0
'''
