type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
2
4 5 3
'''
out = '''
7
'''

[[cases]]
name = "sample2"
in = '''
4
9 7 9 7 10 4 3 9 4 8 10 5 6 3 8
'''
out = '''
15
'''
