type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
4
3 -5 7 -4
'''
out = '''
3
'''

[[cases]]
name = "sample2"
in = '''
5
0 0 0 0 0
'''
out = '''
0
'''

[[cases]]
name = "sample3"
in = '''
4
-1 1000000000 1000000000 1000000000
'''
out = '''
3000000000
'''
