type = "batch"
timelimit = "4s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
5
....#
#..#.
.P...
..P..
....#
'''
out = '''
3
'''

[[cases]]
name = "sample2"
in = '''
2
P#
#P
'''
out = '''
-1
'''

[[cases]]
name = "sample3"
in = '''
10
..........
..........
..........
..........
....P.....
.....P....
..........
..........
..........
..........
'''
out = '''
10
'''
