type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
AtCoder
Total
'''
out = '''
Yes
'''

[[cases]]
name = "sample2"
in = '''
aBCdE
abcdcba
'''
out = '''
No
'''

[[cases]]
name = "sample3"
in = '''
abcde
XYZ
'''
out = '''
Yes
'''
