type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
2 2
'''
out = '''
8
'''

[[cases]]
name = "sample2"
in = '''
3 2
'''
out = '''
12
'''

[[cases]]
name = "sample3"
in = '''
1 8
'''
out = '''
0
'''

[[cases]]
name = "sample4"
in = '''
100000 100000
'''
out = '''
530123477
'''
