type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
5 5
1
2
3
4
5
'''
out = '''
1 2 3 5 4
'''

[[cases]]
name = "sample2"
in = '''
7 7
7
7
7
7
7
7
7
'''
out = '''
1 2 3 4 5 7 6
'''

[[cases]]
name = "sample3"
in = '''
10 6
1
5
2
9
6
6
'''
out = '''
1 2 3 4 5 7 6 8 10 9
'''
