type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
AtCoder
'''
out = '''
atcoder
'''

[[cases]]
name = "sample2"
in = '''
SunTORY
'''
out = '''
SUNTORY
'''

[[cases]]
name = "sample3"
in = '''
a
'''
out = '''
a
'''
