type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
5
'''
out = '''
55555
'''

[[cases]]
name = "sample2"
in = '''
9
'''
out = '''
1755646
'''

[[cases]]
name = "sample3"
in = '''
10000000000
'''
out = '''
468086693
'''
