type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
2 3
sns
euk
'''
out = '''
Yes
'''

[[cases]]
name = "sample2"
in = '''
2 2
ab
cd
'''
out = '''
No
'''

[[cases]]
name = "sample3"
in = '''
5 7
skunsek
nukesnu
ukeseku
nsnnesn
uekukku
'''
out = '''
Yes
'''
