type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
3 3
1 2 3
2 3
1 2 0
2 3
'''
out = '''
15
9
'''

[[cases]]
name = "sample2"
in = '''
2 1
998244353 998244353
2 1
'''
out = '''
0
'''
