type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
20 2 5
'''
out = '''
84
'''

[[cases]]
name = "sample2"
in = '''
10 1 2
'''
out = '''
13
'''

[[cases]]
name = "sample3"
in = '''
100 4 16
'''
out = '''
4554
'''
