type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
2 3
--o
o--
'''
out = '''
3
'''

[[cases]]
name = "sample2"
in = '''
5 4
-o--
----
----
----
-o--
'''
out = '''
4
'''
