type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
?tc????
coder
'''
out = '''
atcoder
'''

[[cases]]
name = "sample2"
in = '''
??p??d??
abc
'''
out = '''
UNRESTORABLE
'''
