type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
AtCoder
'''
out = '''
Yes
'''

[[cases]]
name = "sample2"
in = '''
Aa
'''
out = '''
Yes
'''

[[cases]]
name = "sample3"
in = '''
atcoder
'''
out = '''
No
'''

[[cases]]
name = "sample4"
in = '''
Perfect
'''
out = '''
No
'''
