type = "batch"
timelimit = "3500ms"
match = "lines"

[[cases]]
name = "sample1"
in = '''
2
1 2
'''
out = '''
4
'''

[[cases]]
name = "sample2"
in = '''
3
1 1 1
'''
out = '''
0
'''

[[cases]]
name = "sample3"
in = '''
10
3 1 4 1 5 9 2 6 5 3
'''
out = '''
900221128
'''
