type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
5 5 3 4
#####
#...#
#.@.#
#..@#
#####
LLLDRUU
'''
out = '''
2 3 1
'''

[[cases]]
name = "sample2"
in = '''
6 13 4 6
#############
#@@@@@@@@@@@#
#@@@@@@@@@@@#
#@@@@.@@@@@@#
#@@@@@@@@@@@#
#############
UURUURLRLUUDDURDURRR
'''
out = '''
3 11 11
'''

[[cases]]
name = "sample3"
in = '''
12 35 7 10
###################################
#.................................#
#..........@......................#
#......@................@.........#
#.............##............@.....#
#...##........##....##............#
#...##........##....##.......##...#
#....##......##......##....##.....#
#....##......##......##..##.......#
#.....#######.........###.........#
#.................................#
###################################
LRURRRUUDDULUDUUDLRLRDRRLULRRUDLDRU
'''
out = '''
4 14 1
'''
