type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
0011
'''
out = '''
4
'''

[[cases]]
name = "sample2"
in = '''
11011010001011
'''
out = '''
12
'''

[[cases]]
name = "sample3"
in = '''
0
'''
out = '''
0
'''
