type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
3
4980
7980
6980
'''
out = '''
15950
'''

[[cases]]
name = "sample2"
in = '''
4
4320
4320
4320
4320
'''
out = '''
15120
'''
