type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
-1 -1
-1 2
3 2
'''
out = '''
3 -1
'''

[[cases]]
name = "sample2"
in = '''
-60 -40
-60 -80
-20 -80
'''
out = '''
-20 -40
'''
