type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
2 3
'''
out = '''
3 3
##.
..#
#.#
'''

[[cases]]
name = "sample2"
in = '''
7 8
'''
out = '''
3 5
#.#.#
.#.#.
#.#.#
'''

[[cases]]
name = "sample3"
in = '''
1 1
'''
out = '''
4 2
..
#.
##
##
'''

[[cases]]
name = "sample4"
in = '''
3 14
'''
out = '''
8 18
..................
..................
....##.......####.
....#.#.....#.....
...#...#....#.....
..#.###.#...#.....
.#.......#..#.....
#.........#..####.
'''
