type = "batch"
timelimit = "3s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
8
........
........
.#.##.#.
........
........
........
........
........
'''
out = '''
Yes
'''

[[cases]]
name = "sample2"
in = '''
6
######
######
######
######
######
######
'''
out = '''
Yes
'''

[[cases]]
name = "sample3"
in = '''
10
..........
#..##.....
..........
..........
....#.....
....#.....
.#...#..#.
..........
..........
..........
'''
out = '''
No
'''
