type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
4 5
s####
....#
#####
#...g
'''
out = '''
No
'''

[[cases]]
name = "sample2"
in = '''
4 4
...s
....
....
.g..
'''
out = '''
Yes
'''

[[cases]]
name = "sample3"
in = '''
10 10
s.........
#########.
#.......#.
#..####.#.
##....#.#.
#####.#.#.
g.#.#.#.#.
#.#.#.#.#.
###.#.#.#.
#.....#...
'''
out = '''
No
'''

[[cases]]
name = "sample4"
in = '''
10 10
s.........
#########.
#.......#.
#..####.#.
##....#.#.
#####.#.#.
g.#.#.#.#.
#.#.#.#.#.
#.#.#.#.#.
#.....#...
'''
out = '''
Yes
'''

[[cases]]
name = "sample5"
in = '''
1 10
s..####..g
'''
out = '''
No
'''
