type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
BAC
'''
out = '''
Yes
'''

[[cases]]
name = "sample2"
in = '''
AAC
'''
out = '''
No
'''

[[cases]]
name = "sample3"
in = '''
ABC
'''
out = '''
Yes
'''

[[cases]]
name = "sample4"
in = '''
ARC
'''
out = '''
No
'''
