type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
2 4
1 2
3 4
'''
out = '''
5
'''

[[cases]]
name = "sample2"
in = '''
6 5
1 1
2 2
3 3
4 4
5 5
1 5
'''
out = '''
0
'''

[[cases]]
name = "sample3"
in = '''
6 20
8 12
14 20
11 13
5 19
4 11
1 6
'''
out = '''
102
'''
