type = "batch"
timelimit = "3s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
2 2
1?
??
'''
out = '''
6
'''

[[cases]]
name = "sample2"
in = '''
2 3
123
3?1
'''
out = '''
0
'''

[[cases]]
name = "sample3"
in = '''
8 8
3?1?????
???1????
??????2?
????????
????????
????13??
??13?1??
????????
'''
out = '''
779135038
'''
