type = "batch"
timelimit = "3s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
missisippi
5
i
s
a
is
missisippi
'''
out = '''
4
3
0
2
1
'''

[[cases]]
name = "sample2"
in = '''
aaaaaa
6
a
aa
aaa
aaaa
aaaaa
aaaaaa
'''
out = '''
6
5
4
3
2
1
'''
