type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
54
'''
out = '''
6
'''

[[cases]]
name = "sample2"
in = '''
7
'''
out = '''
4
'''

[[cases]]
name = "sample3"
in = '''
262144
'''
out = '''
19
'''
