type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
2 2
'''
out = '''
2
'''

[[cases]]
name = "sample2"
in = '''
2 3
'''
out = '''
18
'''

[[cases]]
name = "sample3"
in = '''
141421 356237
'''
out = '''
881613484
'''
