type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
100 17
'''
out = '''
83
'''

[[cases]]
name = "sample2"
in = '''
48 58
'''
out = '''
0
'''

[[cases]]
name = "sample3"
in = '''
1000000000 1000000000
'''
out = '''
0
'''
