type = "batch"
timelimit = "2s"
match = "float"

[float]
relative-error = 1e-6
absolute-error = 1e-6

[[cases]]
name = "sample1"
in = '''
3
'''
out = '''
1.000000000000
'''

[[cases]]
name = "sample2"
in = '''
999
'''
out = '''
36926037.000000000000
'''
