type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
ATCODER
'''
out = '''
A......
'''

[[cases]]
name = "sample2"
in = '''
BANANA
'''
out = '''
.A.A.A
'''

[[cases]]
name = "sample3"
in = '''
CORRECT
'''
out = '''
.......
'''
