type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
4 1 10
5 7 5
2 10
'''
out = '''
Yes
'''

[[cases]]
name = "sample2"
in = '''
4 1 10
10 7 5
2 10
'''
out = '''
No
'''
