type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
4 15
9 2 6 5
3 5 8 9
'''
out = '''
6
'''

[[cases]]
name = "sample2"
in = '''
15 100
39 9 36 94 40 26 12 26 28 66 73 85 62 5 20
0 0 7 7 0 5 5 0 7 9 9 4 2 5 2
'''
out = '''
119
'''
