type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
29
'''
out = '''
Yes
'''

[[cases]]
name = "sample2"
in = '''
72
'''
out = '''
No
'''

[[cases]]
name = "sample3"
in = '''
91
'''
out = '''
Yes
'''
