type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
3
6
2
6
'''
out = '''
1
'''

[[cases]]
name = "sample2"
in = '''
4
2
5
5
2
'''
out = '''
0
'''

[[cases]]
name = "sample3"
in = '''
6
12
22
16
22
18
12
'''
out = '''
2
'''
