type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
4 4
....
#.#.
.S..
.##.
'''
out = '''
Yes
'''

[[cases]]
name = "sample2"
in = '''
2 2
S.
.#
'''
out = '''
No
'''

[[cases]]
name = "sample3"
in = '''
5 7
.#...#.
..#.#..
...S...
..#.#..
.#...#.
'''
out = '''
No
'''
