type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
2 900
'''
out = '''
Yes
'''

[[cases]]
name = "sample2"
in = '''
1 501
'''
out = '''
No
'''

[[cases]]
name = "sample3"
in = '''
4 2000
'''
out = '''
Yes
'''
