type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
50 100 120
'''
out = '''
Yes
'''

[[cases]]
name = "sample2"
in = '''
500 100 1000
'''
out = '''
No
'''

[[cases]]
name = "sample3"
in = '''
19 123 143
'''
out = '''
No
'''

[[cases]]
name = "sample4"
in = '''
19 123 142
'''
out = '''
Yes
'''
