type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
isuruu
isleapyear
'''
out = '''
isleapyear
'''

[[cases]]
name = "sample2"
in = '''
ttttiiiimmmmeeee
time
'''
out = '''
ttttiiiimmmmeeee
'''
