type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
4
1 4
2 10
2 8
3 6
'''
out = '''
16
'''

[[cases]]
name = "sample2"
in = '''
4
4 10
3 2
2 4
4 12
'''
out = '''
17
'''
