type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
+-++
'''
out = '''
2
'''

[[cases]]
name = "sample2"
in = '''
-+--
'''
out = '''
-2
'''

[[cases]]
name = "sample3"
in = '''
----
'''
out = '''
-4
'''
