type = "batch"
timelimit = "3s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
6 2
-5 3 4 -1 6 -2
'''
out = '''
7 12 5
'''

[[cases]]
name = "sample2"
in = '''
20 4
-5 3 4 -1 6 -2 13 -1 13 7 6 -12 3 -5 12 -6 -3 10 -15 -5
'''
out = '''
32 45 57 52 22
'''
