type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
3
l0w
1ow
'''
out = '''
Yes
'''

[[cases]]
name = "sample2"
in = '''
3
abc
arc
'''
out = '''
No
'''

[[cases]]
name = "sample3"
in = '''
4
nok0
n0ko
'''
out = '''
Yes
'''
