type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
1 2 3
'''
out = '''
3 1 2
'''

[[cases]]
name = "sample2"
in = '''
100 100 100
'''
out = '''
100 100 100
'''

[[cases]]
name = "sample3"
in = '''
41 59 31
'''
out = '''
31 41 59
'''
