type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
4
naan
'''
out = '''
nyaan
'''

[[cases]]
name = "sample2"
in = '''
4
near
'''
out = '''
near
'''

[[cases]]
name = "sample3"
in = '''
8
national
'''
out = '''
nyationyal
'''
