type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
5 1 2
rrefa
'''
out = '''
3
'''

[[cases]]
name = "sample2"
in = '''
8 1000000000 1000000000
bcdfcgaa
'''
out = '''
4000000000
'''
