type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
3
abc
'''
out = '''
Yes
'''

[[cases]]
name = "sample2"
in = '''
2
ba
'''
out = '''
Yes
'''

[[cases]]
name = "sample3"
in = '''
7
atcoder
'''
out = '''
No
'''
