type = "batch"
timelimit = "2s"
match = "float"

[float]
relative-error = 1e-6
absolute-error = 1e-6

[[cases]]
name = "sample1"
in = '''
3
1000 600 1200
'''
out = '''
256.735020470879931
'''

[[cases]]
name = "sample2"
in = '''
3
600 1000 1200
'''
out = '''
261.423219407873376
'''

[[cases]]
name = "sample3"
in = '''
1
100
'''
out = '''
-1100.000000000000000
'''
