type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
3 2
'''
out = '''
36
'''

[[cases]]
name = "sample2"
in = '''
3 3
'''
out = '''
168
'''

[[cases]]
name = "sample3"
in = '''
12 34
'''
out = '''
539029838
'''

[[cases]]
name = "sample4"
in = '''
20 231104
'''
out = '''
966200489
'''
