type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
7
beat
vet
beet
bed
vet
bet
beet
'''
out = '''
beet
vet
'''

[[cases]]
name = "sample2"
in = '''
8
buffalo
buffalo
buffalo
buffalo
buffalo
buffalo
buffalo
buffalo
'''
out = '''
buffalo
'''

[[cases]]
name = "sample3"
in = '''
7
bass
bass
kick
kick
bass
kick
kick
'''
out = '''
kick
'''

[[cases]]
name = "sample4"
in = '''
4
ushi
tapu
nichia
kun
'''
out = '''
kun
nichia
tapu
ushi
'''
