type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
30 100
'''
out = '''
100
'''

[[cases]]
name = "sample2"
in = '''
12 100
'''
out = '''
50
'''

[[cases]]
name = "sample3"
in = '''
0 100
'''
out = '''
0
'''
