type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
ababbaba
'''
out = '''
8
'''

[[cases]]
name = "sample2"
in = '''
zzz
'''
out = '''
1
'''

[[cases]]
name = "sample3"
in = '''
ppppqqppqqqpqpqppqpqqqqpppqppq
'''
out = '''
580
'''
