type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
100
'''
out = '''
ABC100
'''

[[cases]]
name = "sample2"
in = '''
425
'''
out = '''
ABC425
'''

[[cases]]
name = "sample3"
in = '''
999
'''
out = '''
ABC999
'''
