type = "batch"
timelimit = "2s"
match = "float"

[float]
relative-error = 1e-2
absolute-error = 1e-2

[[cases]]
name = "sample1"
in = '''
100 80
'''
out = '''
20.0
'''

[[cases]]
name = "sample2"
in = '''
7 6
'''
out = '''
14.285714285714285714
'''

[[cases]]
name = "sample3"
in = '''
99999 99998
'''
out = '''
0.00100001000010000100
'''
