type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
5
3
10000
9000
'''
out = '''
48000
'''

[[cases]]
name = "sample2"
in = '''
2
3
10000
9000
'''
out = '''
20000
'''
