type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
3 3
1 2 4
2 3 5
1 3 2
'''
out = '''
1
'''

[[cases]]
name = "sample2"
in = '''
4 4
1 4 7
4 2 2
2 3 4
3 4 1
'''
out = '''
0
'''

[[cases]]
name = "sample3"
in = '''
999 4
1 2 9
2 1 8
1 2 7
1 1 6
'''
out = '''
-1
'''
