type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
3 5
.#...
.....
.#..#
'''
out = '''
9
'''

[[cases]]
name = "sample2"
in = '''
3 3
..#
#..
..#
'''
out = '''
1
'''
