type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
3 2
#.#
.#.
#.#
#.
.#
'''
out = '''
Yes
'''

[[cases]]
name = "sample2"
in = '''
4 1
....
....
....
....
#
'''
out = '''
No
'''
