type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
abcdef
'''
out = '''
badcfe
'''

[[cases]]
name = "sample2"
in = '''
aaaa
'''
out = '''
aaaa
'''

[[cases]]
name = "sample3"
in = '''
atcoderbeginnercontest
'''
out = '''
taocedbrgeniencrnoetts
'''
