type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
5
11/22
'''
out = '''
Yes
'''

[[cases]]
name = "sample2"
in = '''
1
/
'''
out = '''
Yes
'''

[[cases]]
name = "sample3"
in = '''
4
1/22
'''
out = '''
No
'''

[[cases]]
name = "sample4"
in = '''
5
22/11
'''
out = '''
No
'''
