type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
4 4
bbed
abcd
abed
fbed
'''
out = '''
Yes
'''

[[cases]]
name = "sample2"
in = '''
2 5
abcde
abced
'''
out = '''
No
'''

[[cases]]
name = "sample3"
in = '''
8 4
fast
face
cast
race
fact
rice
nice
case
'''
out = '''
Yes
'''
