type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
........
........
........
........
........
........
........
*.......
'''
out = '''
a1
'''

[[cases]]
name = "sample2"
in = '''
........
........
........
........
........
.*......
........
........
'''
out = '''
b3
'''
