type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
5 7
'''
out = '''
8
'''

[[cases]]
name = "sample2"
in = '''
2 5
'''
out = '''
-1
'''

[[cases]]
name = "sample3"
in = '''
100000 10000000000
'''
out = '''
10000000000
'''
