type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
2021 4
'''
out = '''
50531
'''

[[cases]]
name = "sample2"
in = '''
40000 2
'''
out = '''
1
'''

[[cases]]
name = "sample3"
in = '''
8691 20
'''
out = '''
84875488281
'''
