type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
12 30
2023 12 30
'''
out = '''
2024 1 1
'''

[[cases]]
name = "sample2"
in = '''
36 72
6789 23 45
'''
out = '''
6789 23 46
'''

[[cases]]
name = "sample3"
in = '''
12 30
2012 6 20
'''
out = '''
2012 6 21
'''
