type = "batch"
timelimit = "4s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
5
ABCBC
ACAAB
'''
out = '''
Yes
AC..B
.BA.C
C.BA.
BA.C.
..CBA
'''

[[cases]]
name = "sample2"
in = '''
3
AAA
BBB
'''
out = '''
No
'''
