type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
321
'''
out = '''
Yes
'''

[[cases]]
name = "sample2"
in = '''
123
'''
out = '''
No
'''

[[cases]]
name = "sample3"
in = '''
1
'''
out = '''
Yes
'''

[[cases]]
name = "sample4"
in = '''
86411
'''
out = '''
No
'''
