type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
4
1 2
2 3
3 4
WBWW
'''
out = '''
1 2 4 3 
'''

[[cases]]
name = "sample2"
in = '''
4
1 2
2 3
3 4
BBBB
'''
out = '''
-1
'''
