type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
3
'''
out = '''
2
'''

[[cases]]
name = "sample2"
in = '''
5
'''
out = '''
5
'''

[[cases]]
name = "sample3"
in = '''
1000
'''
out = '''
742952024
'''
