type = "batch"
timelimit = "4s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
4 2
5 8 12 20
'''
out = '''
6
'''

[[cases]]
name = "sample2"
in = '''
4 5
24 25 26 27
'''
out = '''
0
'''

[[cases]]
name = "sample3"
in = '''
4 1
24 25 26 27
'''
out = '''
3
'''

[[cases]]
name = "sample4"
in = '''
10 5
39 23 3 7 16 19 40 16 33 6
'''
out = '''
13
'''
