type = "batch"
timelimit = "2s"
match = "lines"

[[cases]]
name = "sample1"
in = '''
3
ab abc arc
'''
out = '''
4
'''

[[cases]]
name = "sample2"
in = '''
11
ab bb aaa bba baba babb aaaba aabbb a a b
'''
out = '''
32
'''
